#--------------------------????-------------------------
spring:
  application:
    name: novel
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
  jackson:
    generator:
      write-numbers-as-strings: true

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

  elasticsearch:
    enabled: false
    rest:
      uris:
        - https://my-deployment-ce7ca3.es.us-central1.gcp.cloud.es.io:9243
      username: elastic
      password: qTjgYVKSuExX6tWAsDuvuvwl


  security:
    user:
      name: ENDPOINT_ADMIN
      password: ENDPOINT_ADMIN
      roles: ENDPOINT_ADMIN
  boot:
    admin:
      client:
        enabled: false


server:
  port: 8888

novel:
  jwt:
    secret: E66559580A1ADF48CDD928516062F12E


--- #---------------------?????---------------------------
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/novel?useUnicode=true&chatacterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  sharding-sphere:
      # 是否开启分库分表
      enabled: false

--- #---------------------?????---------------------------

management:
  health:
    elasticsearch:
      enabled: false
    rabbit:
      enabled: false
